name: Build and Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Universal Android Build
      uses: skylight1/android-build-action@v1
      with:
        project-path: '.'

    - name: Create Update Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: "Latest App Build"
        draft: false
        prerelease: false
        files: '**/build/outputs/apk/**/*.apk'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
